### ISSUE TITLE
how use another API methods?

### ISSUE THREAD

**Issue by rostyslav-andrushko** [meritoo/limesurvey-api-client#2]
How to use limesurvey api methods that are not in MethodType?

**Comment by kniziol** [comment]
@rostandr Sorry for the delay. I've missed notification. It's impossible to run method other than defined in `\Meritoo\LimeSurvey\ApiClient\Type\MethodType` or in `\Meritoo\LimeSurvey\ApiClient\Type\SystemMethodType` class right now. Which method would you like to run?

**Comment by meritoo** [comment]
@rostandr Sorry for the delay. We've missed notification. It's impossible to run method other than defined in `\Meritoo\LimeSurvey\ApiClient\Type\MethodType` or in `\Meritoo\LimeSurvey\ApiClient\Type\SystemMethodType` class right now.

Which method would you like to run? We will add those methods.
